name: DAI_MR_RAA
channels:
  - defaults
dependencies:
  - anyio
  - argon2-cffi
  - argon2-cffi-bindings
  - asttokens
  - async-lru
  - attrs
  - babel
  - beautifulsoup4
  - blas
  - bleach
  - bottleneck
  - brotli
  - brotli-bin
  - brotli-python
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - comm
  - contourpy
  - cycler
  - cyrus-sasl
  - debugpy
  - decorator
  - defusedxml
  - exceptiongroup
  - executing
  - fonttools
  - freetype
  - glib
  - glib-tools
  - gst-plugins-base
  - gstreamer
  - h11
  - httpcore
  - httpx
  - icu
  - idna
  - ipykernel
  - ipython
  - ipywidgets
  - jedi
  - jinja2
  - joblib
  - jpeg
  - json5
  - jsonschema
  - jsonschema-specifications
  - jupyter
  - jupyter-lsp
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libclang
  - libclang13
  - libdeflate
  - libffi
  - libglib
  - libiconv
  - libllvm14
  - libpng
  - libpq
  - libsodium
  - libtiff
  - libwebp-base
  - libxml2
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - nbclient
  - nbconvert
  - nbformat
  - nest-asyncio
  - notebook
  - notebook-shim
  - numexpr
  - numpy
  - numpy-base
  - openjpeg
  - openssl
  - overrides
  - packaging
  - pandas
  - pandocfilters
  - parso
  - pcre2
  - pexpect
  - pillow
  - pip
  - platformdirs
  - ply
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - pybind11-abi
  - pycparser
  - pygments
  - pyparsing
  - pyqt
  - pyqt5-sip
  - pysocks
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - python-tzdata
  - pytz
  - pyyaml
  - pyzmq
  - qt-main
  - qtconsole
  - qtpy
  - referencing
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - rpds-py
  - scikit-learn
  - scipy
  - send2trash
  - setuptools
  - sip
  - six
  - sniffio
  - soupsieve
  - sqlite
  - stack_data
  - terminado
  - threadpoolctl
  - tinycss2
  - tk
  - tornado
  - tqdm
  - traitlets
  - tzdata
  - typing-extensions
  - urllib3
  - wcwidth
  - webencodings
  - webob
  - wheel
  - widgetsnbextension
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd
